import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { render, writeExport } from '../lib/render.mjs';
const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'cv-contracts-'));
const sourceProject = path.join(root, 'Structured CV template');
const project = path.join(temp, 'project');
fs.cpSync(sourceProject, project, { recursive:true });
const source = path.join(project, 'cv.html');
const personFile = path.join(project, 'content/person.json');
const person = JSON.parse(fs.readFileSync(personFile, 'utf8'));
const update = value => fs.writeFileSync(personFile, JSON.stringify(value));
try {
  const options = { source, profile:'mba', theme:'classic' };
  const initial = render(options);
  assert.equal(initial, render(options), 'Builds must be deterministic');
  assert.throws(() => render({...options,profile:'../mba'}), /Invalid profile/);
  assert.throws(() => render({...options,profile:'missing'}), /ENOENT/);
  const roleFile = path.join(project,'content/experience/recent-role.json');
  const originalRole = fs.readFileSync(roleFile,'utf8');
  const invalidRole = JSON.parse(originalRole);
  invalidRole.variants.mba.main = [999];
  fs.writeFileSync(roleFile,JSON.stringify(invalidRole));
  assert.throws(() => render(options), /Invalid paragraph index/);
  fs.writeFileSync(roleFile,originalRole);
  update({...person, name:'<script>alert("x")</script> & Your Name'});
  assert.match(render(options), /&lt;script&gt;alert\(&quot;x&quot;\)&lt;\/script&gt; &amp; Your Name/);
  update({...person, contacts:[{label:'Website',value:'Click',href:'javascript:alert(1)'}]});
  assert.throws(() => render(options), /Unsupported contact link/);
  update(person);
  assert.throws(() => writeExport({...options,out:source},'check'), /overwrite source/);
  const protectedFile = path.join(temp, 'existing.html');
  fs.writeFileSync(protectedFile, 'My hand-edited file');
  assert.throws(() => writeExport({...options,out:protectedFile},'check'), /non-generated file/);
  assert.equal(fs.readFileSync(protectedFile,'utf8'), 'My hand-edited file');
  const exported = path.join(temp, 'portable.html');
  writeExport({...options,theme:'editorial',out:exported},'check');
  assert.match(fs.readFileSync(exported,'utf8'), /url\("data:font\/ttf;base64,/);
  assert.match(fs.readFileSync(exported,'utf8'), /SIL OPEN FONT LICENSE/);
  fs.writeFileSync(path.join(project,'styles/unsafe.css'),'@import "https://example.com/font.css";');
  assert.throws(() => render({...options,theme:'unsafe'}), /@import/);
  fs.writeFileSync(path.join(project,'styles/unsafe.css'),'@font-face{src:url("../../outside.ttf")}');
  fs.writeFileSync(path.join(temp,'outside.ttf'),'not a real font');
  assert.throws(() => render({...options,theme:'unsafe'}), /escapes project/);
  const profileFile = path.join(project,'content/profiles/mba.json');
  const profile = JSON.parse(fs.readFileSync(profileFile,'utf8'));
  profile.pages.push(profile.pages[0]);
  fs.writeFileSync(profileFile,JSON.stringify(profile));
  assert.throws(() => render(options), /exactly two pages/);
  console.log('PASS: deterministic output, text escaping, invalid references, links, source protection, embedded fonts, path containment, page count contract');
} finally {
  assert.equal(path.dirname(fs.realpathSync(temp)), fs.realpathSync(os.tmpdir()));
  assert.ok(path.basename(temp).startsWith('cv-contracts-'));
  fs.rmSync(temp, { recursive:true, force:true });
}
